### ISSUE TITLE
Crash - RPG Loot Even Handler Sound Issue

### ISSUE THREAD

**Issue by DPxKnightxZero** [FusionLord/RPGLoot#2]
Partial Log - RPG Loot Event Handler 
https://gist.github.com/DPxKnightxZero/2e35e6a41505e28f5f6a

Full Log - Server Log With Crash RPG Loot Event Handler
https://gist.github.com/DPxKnightxZero/9f9085e544b28f1cd8db

**Comment by FusionLord** [comment]
I have fixed this issue in the [1.7.10] 1.0.1 version. Sorry it has taken me this long, I didn't get a notification about this issue post.
