### ISSUE TITLE
Issue with corpse rendering.

### ISSUE THREAD

**Issue by Claycorp** [FusionLord/RPGLoot#3]
If you kill a mob the corpse will 'pulse' because it is rapidly changing sizes.
I assume this could be a compatibility issue with fathertoasts special mobs because you can set mobs to have different sizes. It happens only to vanilla mobs as those are the ones that are edited 
Example: Creepers can be 15% bigger or smaller than the default model.

**Comment by FusionLord** [comment]
This is an issue with FatherToasts special mobs, as I pass the rendering off to the owner of the entity.
